# **Import Libraries**

In [1]:
import numpy as np
import pandas as pd

# **Mount Drive**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# **Load Data**

In [3]:
customer_data=pd.read_excel('/content/drive/MyDrive/Projects/Customer Segmentation/Data/customer_data.xlsx')
sales_data=pd.read_excel('/content/drive/MyDrive/Projects/Customer Segmentation/Data/sales_data.xlsx')
shoping_data=pd.read_excel('/content/drive/MyDrive/Projects/Customer Segmentation/Data/shopping_mall_data.xlsx')

## **Merging three tables**

In [4]:
customer_data.columns

Index(['customer_id', 'gender', 'age', 'payment_method'], dtype='object')

In [5]:
sales_data.columns

Index(['invoice_no', 'customer_id', 'category', 'quantity', 'invoice date',
       'price', 'shopping_mall'],
      dtype='object')

In [6]:
shoping_data.columns

Index(['shopping_mall', 'construction_year', 'area (sqm)', 'location',
       'store_count'],
      dtype='object')

In [7]:
df = pd.merge(customer_data, sales_data, on='customer_id', how='inner')
merged_df=pd.merge(df, shoping_data, on='shopping_mall', how='left')

In [8]:
merged_df.columns

Index(['customer_id', 'gender', 'age', 'payment_method', 'invoice_no',
       'category', 'quantity', 'invoice date', 'price', 'shopping_mall',
       'construction_year', 'area (sqm)', 'location', 'store_count'],
      dtype='object')

In [9]:
merged_df.sample(10)

,customer_id,gender,age,payment_method,invoice_no,category,quantity,invoice date,price,shopping_mall,construction_year,area (sqm),location,store_count
30232,C155703,Male,59.0,Cash,I270129,Toys,2,02/10/2022,71.68,Fashion Valley,1977.0,161000.0,San Diego,180.0
2169,C193054,Male,44.0,Cash,I809166,Shoes,5,06/10/2021,3000.85,Beverly Center,1982.0,111000.0,Los Angeles,160.0
21551,C131550,Female,68.0,Cash,I961459,Shoes,3,11/11/2021,1800.51,Glendale Galleria,1976.0,145000.0,Glendale,190.0
46291,C444377,Male,39.0,Cash,I357987,Cosmetics,2,12/06/2021,81.32,Stanford Shopping Center,1956.0,120000.0,Palo Alto,140.0
38847,C244924,Female,46.0,Cash,I157966,Clothing,3,06/18/2021,900.24,Westfield Valley Fair,1986.0,220000.0,Santa Clara,230.0
55221,C156219,Female,42.0,Cash,I195822,Shoes,4,09/19/2022,2400.68,South Coast Plaza,1967.0,250000.0,Costa Mesa,270.0
24783,C157724,Male,36.0,Credit Card,I209716,Clothing,3,04/06/2022,900.24,Westfield Valley Fair,1986.0,220000.0,Santa Clara,230.0
18172,C187983,Male,54.0,Cash,I296754,Food & Beverage,5,03/17/2021,26.15,Westfield Century City,1964.0,133000.0,Los Angeles,200.0
12804,C193933,Male,64.0,Credit Card,I240907,Toys,4,06/16/2021,143.36,Glendale Galleria,1976.0,145000.0,Glendale,190.0
42274,C149731,Male,47.0,Cash,I227688,Food & Beverage,1,07/03/2023,5.23,Westfield Valley Fair,1986.0,220000.0,Santa Clara,230.0

## **Converting to customer level data**

In [10]:
final_df = merged_df.groupby('customer_id').agg({
    'age': 'first',
    'gender': 'first',
    'payment_method': 'first',
    'quantity': 'sum',
    'price': 'sum',
    'invoice_no': 'count',   # number of purchases
    'store_count': 'mean'
}).reset_index()

In [11]:
final_df

,customer_id,age,gender,payment_method,quantity,price,invoice_no,store_count
0,C100004,61.0,Male,Credit Card,5,1500.40,1,200.0
1,C100005,34.0,Male,Cash,2,1200.34,1,270.0
2,C100006,44.0,Male,Credit Card,3,107.52,1,NaN
3,C100012,25.0,Male,Cash,5,26.15,1,270.0
4,C100019,21.0,Female,Credit Card,1,35.84,1,200.0
...,...,...,...,...,...,...,...,...
99452,C999886,61.0,Male,Debit Card,3,15.69,1,270.0
99453,C999910,41.0,Male,Debit Card,3,45.45,1,220.0
99454,C999974,29.0,Female,Cash,5,1500.40,1,160.0
99455,C999976,49.0,Female,Debit Card,3,107.52,1,200.0
99456,C999995,57.0,Female,Cash,2,600.16,1,270.0

## **Renaming some Columns**

In [12]:
final_df.rename(columns={
    'invoice_no': 'purchase_count',
    'price': 'total_spent'
}, inplace=True)

In [13]:
final_df.head()

,customer_id,age,gender,payment_method,quantity,total_spent,purchase_count,store_count
0,C100004,61.0,Male,Credit Card,5,1500.40,1,200.0
1,C100005,34.0,Male,Cash,2,1200.34,1,270.0
2,C100006,44.0,Male,Credit Card,3,107.52,1,NaN
3,C100012,25.0,Male,Cash,5,26.15,1,270.0
4,C100019,21.0,Female,Credit Card,1,35.84,1,200.0

In [14]:
final_df.to_csv('/content/drive/MyDrive/Projects/Customer Segmentation/Data/Final_merged_dataset.csv')